[project]
name = "asyncapi-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "langchain>=0.3.24",
    "nltk>=3.9.1",
    "ollama>=0.4.8",
    "qdrant-client>=1.14.2",
]
